[package]
name = "wkb_wkt_converter_py"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Python bindings for wkb_wkt_converter"
publish = false

[lib]
name = "wkb_wkt_converter_py"
crate-type = ["cdylib"]

[dependencies]
wkb_wkt_converter = { path = "../wkb_wkt_converter" }
pyo3 = { version = "0.28", features = ["extension-module"] }
