/// WKB → WKT tests.
///
/// Most fixtures are generated by `wkt_to_wkb` so we avoid hand-encoding bytes
/// (error-prone). The exceptions are tests that specifically exercise known
/// external binary representations (ISO WKB, SRID-embedded EWKB).
use wkb_wkt_converter::{wkb_to_wkt, wkb_to_wkt_split_srid, wkt_to_wkb, hex_wkb_to_wkt};

fn wkb_of(wkt: &str) -> Vec<u8> {
    wkt_to_wkb(wkt).unwrap()
}

// ── Point ────────────────────────────────────────────────────────────────────

#[test]
fn point_xy() {
    assert_eq!(wkb_to_wkt(&wkb_of("POINT (1 2)")).unwrap(), "POINT (1 2)");
}

#[test]
fn point_xyz() {
    assert_eq!(wkb_to_wkt(&wkb_of("POINT Z (1 2 3)")).unwrap(), "POINT Z (1 2 3)");
}

#[test]
fn point_xym() {
    assert_eq!(wkb_to_wkt(&wkb_of("POINT M (1 2 3)")).unwrap(), "POINT M (1 2 3)");
}

#[test]
fn point_xyzm() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("POINT ZM (1 2 3 4)")).unwrap(),
        "POINT ZM (1 2 3 4)"
    );
}

#[test]
fn point_empty() {
    assert_eq!(wkb_to_wkt(&wkb_of("POINT EMPTY")).unwrap(), "POINT EMPTY");
}

#[test]
fn point_empty_z() {
    assert_eq!(wkb_to_wkt(&wkb_of("POINT Z EMPTY")).unwrap(), "POINT Z EMPTY");
}

/// Externally-crafted EWKB with SRID=4326 for POINT (1 2).
/// Byte layout: 01 01000020 E6100000 000000000000F03F 0000000000000040
#[test]
fn point_with_srid_embedded_ewkb() {
    let mut wkb = vec![0x01u8];                             // LE
    wkb.extend_from_slice(&0x2000_0001u32.to_le_bytes());   // type=Point | EWKB_SRID
    wkb.extend_from_slice(&4326u32.to_le_bytes());          // SRID
    wkb.extend_from_slice(&1.0f64.to_le_bytes());           // x
    wkb.extend_from_slice(&2.0f64.to_le_bytes());           // y
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "SRID=4326;POINT (1 2)");
}

#[test]
fn point_split_srid() {
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&0x2000_0001u32.to_le_bytes());
    wkb.extend_from_slice(&4326u32.to_le_bytes());
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&2.0f64.to_le_bytes());
    let (wkt, srid) = wkb_to_wkt_split_srid(&wkb).unwrap();
    assert_eq!(wkt, "POINT (1 2)");
    assert_eq!(srid, Some(4326));
}

#[test]
fn point_no_srid_split() {
    let (wkt, srid) = wkb_to_wkt_split_srid(&wkb_of("POINT (1 2)")).unwrap();
    assert_eq!(wkt, "POINT (1 2)");
    assert_eq!(srid, None);
}

// ── ISO WKB (non-EWKB, dimension via type offset) ────────────────────────────

/// ISO WKB encodes XYZ as type+1000. Verify we decode it correctly.
#[test]
fn iso_wkb_point_xyz() {
    let mut wkb = vec![0x01u8]; // LE
    wkb.extend_from_slice(&1001u32.to_le_bytes()); // Point + 1000 = XYZ
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&2.0f64.to_le_bytes());
    wkb.extend_from_slice(&3.0f64.to_le_bytes());
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "POINT Z (1 2 3)");
}

#[test]
fn iso_wkb_point_xym() {
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&2001u32.to_le_bytes()); // Point + 2000 = XYM
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&2.0f64.to_le_bytes());
    wkb.extend_from_slice(&3.0f64.to_le_bytes());
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "POINT M (1 2 3)");
}

#[test]
fn iso_wkb_point_xyzm() {
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&3001u32.to_le_bytes()); // Point + 3000 = XYZM
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&2.0f64.to_le_bytes());
    wkb.extend_from_slice(&3.0f64.to_le_bytes());
    wkb.extend_from_slice(&4.0f64.to_le_bytes());
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "POINT ZM (1 2 3 4)");
}

// ── Big-endian WKB ───────────────────────────────────────────────────────────

#[test]
fn big_endian_point() {
    let mut wkb = vec![0x00u8]; // BE
    wkb.extend_from_slice(&1u32.to_be_bytes()); // type = Point XY
    wkb.extend_from_slice(&1.0f64.to_be_bytes());
    wkb.extend_from_slice(&2.0f64.to_be_bytes());
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "POINT (1 2)");
}

// ── LineString ───────────────────────────────────────────────────────────────

#[test]
fn linestring_xy() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("LINESTRING (0 0, 1 1, 2 2)")).unwrap(),
        "LINESTRING (0 0, 1 1, 2 2)"
    );
}

#[test]
fn linestring_xyz() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("LINESTRING Z (0 0 0, 1 1 1)")).unwrap(),
        "LINESTRING Z (0 0 0, 1 1 1)"
    );
}

#[test]
fn linestring_empty() {
    assert_eq!(wkb_to_wkt(&wkb_of("LINESTRING EMPTY")).unwrap(), "LINESTRING EMPTY");
}

// ── Polygon ──────────────────────────────────────────────────────────────────

#[test]
fn polygon_one_ring() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))")).unwrap(),
        "POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))"
    );
}

#[test]
fn polygon_with_hole() {
    let wkt = "POLYGON ((0 0, 10 0, 10 10, 0 10, 0 0), (1 1, 1 9, 9 9, 9 1, 1 1))";
    assert_eq!(wkb_to_wkt(&wkb_of(wkt)).unwrap(), wkt);
}

#[test]
fn polygon_empty() {
    assert_eq!(wkb_to_wkt(&wkb_of("POLYGON EMPTY")).unwrap(), "POLYGON EMPTY");
}

// ── Multi-geometries ─────────────────────────────────────────────────────────

#[test]
fn multipoint_xy() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("MULTIPOINT ((0 0), (1 1))")).unwrap(),
        "MULTIPOINT ((0 0), (1 1))"
    );
}

#[test]
fn multilinestring_xy() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("MULTILINESTRING ((0 0, 1 1), (2 2, 3 3))")).unwrap(),
        "MULTILINESTRING ((0 0, 1 1), (2 2, 3 3))"
    );
}

#[test]
fn multipolygon_xy() {
    let wkt = "MULTIPOLYGON (((0 0, 1 0, 1 1, 0 0)), ((2 2, 3 2, 3 3, 2 2)))";
    assert_eq!(wkb_to_wkt(&wkb_of(wkt)).unwrap(), wkt);
}

#[test]
fn geometrycollection_xy() {
    let wkt = "GEOMETRYCOLLECTION (POINT (1 2), LINESTRING (0 0, 1 1))";
    assert_eq!(wkb_to_wkt(&wkb_of(wkt)).unwrap(), wkt);
}

#[test]
fn multipoint_empty() {
    assert_eq!(wkb_to_wkt(&wkb_of("MULTIPOINT EMPTY")).unwrap(), "MULTIPOINT EMPTY");
}

#[test]
fn geometrycollection_empty() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("GEOMETRYCOLLECTION EMPTY")).unwrap(),
        "GEOMETRYCOLLECTION EMPTY"
    );
}

// ── Hex convenience ──────────────────────────────────────────────────────────

#[test]
fn hex_wkb_to_wkt_point() {
    // Generate hex from known WKT, then verify round-trip via hex helper
    use wkb_wkt_converter::wkt_to_hex_wkb;
    let hex = wkt_to_hex_wkb("POINT (1 2)").unwrap();
    assert_eq!(hex_wkb_to_wkt(&hex).unwrap(), "POINT (1 2)");
}

#[test]
fn hex_wkb_odd_length_error() {
    assert!(hex_wkb_to_wkt("ABC").is_err());
}

#[test]
fn hex_wkb_invalid_chars_error() {
    assert!(hex_wkb_to_wkt("ZZZZ").is_err());
}

// ── Error cases ──────────────────────────────────────────────────────────────

#[test]
fn empty_input_errors() {
    assert!(wkb_to_wkt(&[]).is_err());
}

#[test]
fn invalid_byte_order_errors() {
    assert!(wkb_to_wkt(&[0x02, 0x01, 0x00, 0x00, 0x00]).is_err());
}

#[test]
fn truncated_wkb_errors() {
    // Valid header for POINT XY but only one coordinate (Y missing)
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&1u32.to_le_bytes());
    wkb.extend_from_slice(&1.0f64.to_le_bytes()); // x only
    assert!(wkb_to_wkt(&wkb).is_err());
}

#[test]
fn unsupported_type_errors() {
    // Type code 99 is not a valid geometry type
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&99u32.to_le_bytes());
    assert!(wkb_to_wkt(&wkb).is_err());
}
