/// WKB → WKT tests.
///
/// Most fixtures are generated by `wkt_to_wkb` so we avoid hand-encoding bytes
/// (error-prone). The exceptions are tests that specifically exercise known
/// external binary representations (ISO WKB, SRID-embedded EWKB).
use wkb_wkt_converter::{hex_wkb_to_wkt, wkb_to_wkt, wkb_to_wkt_split_srid, wkt_to_wkb};

fn wkb_of(wkt: &str) -> Vec<u8> {
    wkt_to_wkb(wkt).unwrap()
}

fn le_header(geom_type: u32) -> Vec<u8> {
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&geom_type.to_le_bytes());
    wkb
}

fn le_point_with_coords(geom_type: u32, coords: &[f64]) -> Vec<u8> {
    let mut wkb = le_header(geom_type);
    for coord in coords {
        wkb.extend_from_slice(&coord.to_le_bytes());
    }
    wkb
}

fn nested_geometrycollection_wkb(collection_depth: usize) -> Vec<u8> {
    let mut wkb = Vec::new();
    for _ in 0..collection_depth {
        wkb.push(0x01);
        wkb.extend_from_slice(&7u32.to_le_bytes());
        wkb.extend_from_slice(&1u32.to_le_bytes());
    }
    wkb.extend_from_slice(&wkb_of("POINT (1 2)"));
    wkb
}

// ── Point ────────────────────────────────────────────────────────────────────

#[test]
fn point_xy() {
    assert_eq!(wkb_to_wkt(&wkb_of("POINT (1 2)")).unwrap(), "POINT (1 2)");
}

#[test]
fn point_xyz() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("POINT Z (1 2 3)")).unwrap(),
        "POINT Z (1 2 3)"
    );
}

#[test]
fn point_xym() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("POINT M (1 2 3)")).unwrap(),
        "POINT M (1 2 3)"
    );
}

#[test]
fn point_xyzm() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("POINT ZM (1 2 3 4)")).unwrap(),
        "POINT ZM (1 2 3 4)"
    );
}

#[test]
fn point_empty() {
    assert_eq!(wkb_to_wkt(&wkb_of("POINT EMPTY")).unwrap(), "POINT EMPTY");
}

#[test]
fn point_empty_z() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("POINT Z EMPTY")).unwrap(),
        "POINT Z EMPTY"
    );
}

#[test]
fn point_partial_nan_errors() {
    let wkb = le_point_with_coords(1, &[f64::NAN, 2.0]);
    assert!(wkb_to_wkt(&wkb).is_err());
}

#[test]
fn point_infinity_errors() {
    let wkb = le_point_with_coords(1, &[f64::INFINITY, 2.0]);
    assert!(wkb_to_wkt(&wkb).is_err());
}

#[test]
fn point_negative_zero_formats_as_zero() {
    assert_eq!(wkb_to_wkt(&wkb_of("POINT (-0 -0)")).unwrap(), "POINT (0 0)");
}

/// Externally-crafted EWKB with SRID=4326 for POINT (1 2).
/// Byte layout: 01 01000020 E6100000 000000000000F03F 0000000000000040
#[test]
fn point_with_srid_embedded_ewkb() {
    let mut wkb = vec![0x01u8]; // LE
    wkb.extend_from_slice(&0x2000_0001u32.to_le_bytes()); // type=Point | EWKB_SRID
    wkb.extend_from_slice(&4326u32.to_le_bytes()); // SRID
    wkb.extend_from_slice(&1.0f64.to_le_bytes()); // x
    wkb.extend_from_slice(&2.0f64.to_le_bytes()); // y
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "SRID=4326;POINT (1 2)");
}

#[test]
fn point_split_srid() {
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&0x2000_0001u32.to_le_bytes());
    wkb.extend_from_slice(&4326u32.to_le_bytes());
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&2.0f64.to_le_bytes());
    let (wkt, srid) = wkb_to_wkt_split_srid(&wkb).unwrap();
    assert_eq!(wkt, "POINT (1 2)");
    assert_eq!(srid, Some(4326));
}

#[test]
fn point_no_srid_split() {
    let (wkt, srid) = wkb_to_wkt_split_srid(&wkb_of("POINT (1 2)")).unwrap();
    assert_eq!(wkt, "POINT (1 2)");
    assert_eq!(srid, None);
}

// ── ISO WKB (non-EWKB, dimension via type offset) ────────────────────────────

/// ISO WKB encodes XYZ as type+1000. Verify we decode it correctly.
#[test]
fn iso_wkb_point_xyz() {
    let mut wkb = vec![0x01u8]; // LE
    wkb.extend_from_slice(&1001u32.to_le_bytes()); // Point + 1000 = XYZ
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&2.0f64.to_le_bytes());
    wkb.extend_from_slice(&3.0f64.to_le_bytes());
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "POINT Z (1 2 3)");
}

#[test]
fn iso_wkb_point_xym() {
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&2001u32.to_le_bytes()); // Point + 2000 = XYM
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&2.0f64.to_le_bytes());
    wkb.extend_from_slice(&3.0f64.to_le_bytes());
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "POINT M (1 2 3)");
}

#[test]
fn iso_wkb_point_xyzm() {
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&3001u32.to_le_bytes()); // Point + 3000 = XYZM
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&2.0f64.to_le_bytes());
    wkb.extend_from_slice(&3.0f64.to_le_bytes());
    wkb.extend_from_slice(&4.0f64.to_le_bytes());
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "POINT ZM (1 2 3 4)");
}

// ── Big-endian WKB ───────────────────────────────────────────────────────────

#[test]
fn big_endian_point() {
    let mut wkb = vec![0x00u8]; // BE
    wkb.extend_from_slice(&1u32.to_be_bytes()); // type = Point XY
    wkb.extend_from_slice(&1.0f64.to_be_bytes());
    wkb.extend_from_slice(&2.0f64.to_be_bytes());
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "POINT (1 2)");
}

// ── LineString ───────────────────────────────────────────────────────────────

#[test]
fn linestring_xy() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("LINESTRING (0 0, 1 1, 2 2)")).unwrap(),
        "LINESTRING (0 0, 1 1, 2 2)"
    );
}

#[test]
fn linestring_xyz() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("LINESTRING Z (0 0 0, 1 1 1)")).unwrap(),
        "LINESTRING Z (0 0 0, 1 1 1)"
    );
}

#[test]
fn linestring_empty() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("LINESTRING EMPTY")).unwrap(),
        "LINESTRING EMPTY"
    );
}

#[test]
fn linestring_nan_coordinate_errors() {
    let mut wkb = le_header(2);
    wkb.extend_from_slice(&1u32.to_le_bytes());
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&f64::NAN.to_le_bytes());
    assert!(wkb_to_wkt(&wkb).is_err());
}

// ── Polygon ──────────────────────────────────────────────────────────────────

#[test]
fn polygon_one_ring() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))")).unwrap(),
        "POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))"
    );
}

#[test]
fn polygon_with_hole() {
    let wkt = "POLYGON ((0 0, 10 0, 10 10, 0 10, 0 0), (1 1, 1 9, 9 9, 9 1, 1 1))";
    assert_eq!(wkb_to_wkt(&wkb_of(wkt)).unwrap(), wkt);
}

#[test]
fn polygon_empty() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("POLYGON EMPTY")).unwrap(),
        "POLYGON EMPTY"
    );
}

// ── Multi-geometries ─────────────────────────────────────────────────────────

#[test]
fn multipoint_xy() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("MULTIPOINT ((0 0), (1 1))")).unwrap(),
        "MULTIPOINT ((0 0), (1 1))"
    );
}

#[test]
fn multilinestring_xy() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("MULTILINESTRING ((0 0, 1 1), (2 2, 3 3))")).unwrap(),
        "MULTILINESTRING ((0 0, 1 1), (2 2, 3 3))"
    );
}

#[test]
fn multipolygon_xy() {
    let wkt = "MULTIPOLYGON (((0 0, 1 0, 1 1, 0 0)), ((2 2, 3 2, 3 3, 2 2)))";
    assert_eq!(wkb_to_wkt(&wkb_of(wkt)).unwrap(), wkt);
}

#[test]
fn geometrycollection_xy() {
    let wkt = "GEOMETRYCOLLECTION (POINT (1 2), LINESTRING (0 0, 1 1))";
    assert_eq!(wkb_to_wkt(&wkb_of(wkt)).unwrap(), wkt);
}

#[test]
fn geometrycollection_xy_parent_allows_heterogeneous_children() {
    let wkt = "GEOMETRYCOLLECTION (POINT Z (1 2 3), POINT M (4 5 6))";
    assert_eq!(wkb_to_wkt(&wkb_of(wkt)).unwrap(), wkt);
}

#[test]
fn geometrycollection_non_xy_parent_requires_matching_child_dimensions() {
    let wkt = "GEOMETRYCOLLECTION Z (POINT Z (1 2 3))";
    assert_eq!(wkb_to_wkt(&wkb_of(wkt)).unwrap(), wkt);

    let mut wkb = le_header(0x8000_0007); // GeometryCollection Z
    wkb.extend_from_slice(&1u32.to_le_bytes());
    wkb.extend_from_slice(&wkb_of("POINT (1 2)"));
    assert!(wkb_to_wkt(&wkb).is_err());
}

#[test]
fn multipoint_empty() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("MULTIPOINT EMPTY")).unwrap(),
        "MULTIPOINT EMPTY"
    );
}

#[test]
fn geometrycollection_empty() {
    assert_eq!(
        wkb_to_wkt(&wkb_of("GEOMETRYCOLLECTION EMPTY")).unwrap(),
        "GEOMETRYCOLLECTION EMPTY"
    );
}

// ── Hex convenience ──────────────────────────────────────────────────────────

#[test]
fn hex_wkb_to_wkt_point() {
    // Generate hex from known WKT, then verify round-trip via hex helper
    use wkb_wkt_converter::wkt_to_hex_wkb;
    let hex = wkt_to_hex_wkb("POINT (1 2)").unwrap();
    assert_eq!(hex_wkb_to_wkt(&hex).unwrap(), "POINT (1 2)");
}

#[test]
fn hex_wkb_odd_length_error() {
    assert!(hex_wkb_to_wkt("ABC").is_err());
}

#[test]
fn hex_wkb_invalid_chars_error() {
    assert!(hex_wkb_to_wkt("ZZZZ").is_err());
}

// ── Error cases ──────────────────────────────────────────────────────────────

#[test]
fn empty_input_errors() {
    assert!(wkb_to_wkt(&[]).is_err());
}

#[test]
fn invalid_byte_order_errors() {
    assert!(wkb_to_wkt(&[0x02, 0x01, 0x00, 0x00, 0x00]).is_err());
}

#[test]
fn truncated_wkb_errors() {
    // Valid header for POINT XY but only one coordinate (Y missing)
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&1u32.to_le_bytes());
    wkb.extend_from_slice(&1.0f64.to_le_bytes()); // x only
    assert!(wkb_to_wkt(&wkb).is_err());
}

#[test]
fn unsupported_type_errors() {
    // Type code 99 is not a valid geometry type
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&99u32.to_le_bytes());
    assert!(wkb_to_wkt(&wkb).is_err());
}

#[test]
fn truncated_before_type_code_errors() {
    // Byte-order byte present but only 2 of the 4 type-code bytes available
    assert!(wkb_to_wkt(&[0x01, 0x01, 0x00]).is_err());
}

#[test]
fn top_level_trailing_bytes_error() {
    let mut wkb = wkb_of("POINT (1 2)");
    wkb.extend_from_slice(&[0xDE, 0xAD, 0xBE, 0xEF]);
    assert!(wkb_to_wkt(&wkb).is_err());
    assert!(wkb_to_wkt_split_srid(&wkb).is_err());
    assert!(hex_wkb_to_wkt(&hex::encode_upper(&wkb)).is_err());
}

#[test]
fn geometry_depth_limit_is_enforced_for_wkb() {
    assert!(wkb_to_wkt(&nested_geometrycollection_wkb(127)).is_ok());
    assert!(wkb_to_wkt(&nested_geometrycollection_wkb(128)).is_err());
}

// ── MultiPoint edge cases ─────────────────────────────────────────────────────

#[test]
fn multipoint_with_empty_sub_point() {
    // A MultiPoint containing one real point and one EMPTY (NaN) sub-point.
    // The reader should render the EMPTY sub-point as "EMPTY" (no parens).
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&4u32.to_le_bytes()); // MultiPoint
    wkb.extend_from_slice(&2u32.to_le_bytes()); // 2 members
                                                // Member 1: normal point (1, 2)
    wkb.push(0x01);
    wkb.extend_from_slice(&1u32.to_le_bytes()); // Point
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&2.0f64.to_le_bytes());
    // Member 2: EMPTY point (NaN, NaN)
    wkb.push(0x01);
    wkb.extend_from_slice(&1u32.to_le_bytes()); // Point
    wkb.extend_from_slice(&f64::NAN.to_le_bytes());
    wkb.extend_from_slice(&f64::NAN.to_le_bytes());
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "MULTIPOINT ((1 2), EMPTY)");
}

#[test]
fn multipoint_wrong_subtype_errors() {
    // A MultiPoint whose sole member is a LineString — must be rejected.
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&4u32.to_le_bytes()); // MultiPoint
    wkb.extend_from_slice(&1u32.to_le_bytes()); // 1 member
    wkb.push(0x01);
    wkb.extend_from_slice(&2u32.to_le_bytes()); // LineString (not Point)
    wkb.extend_from_slice(&0u32.to_le_bytes()); // 0 points
    assert!(wkb_to_wkt(&wkb).is_err());
}

#[test]
fn multipoint_child_dimension_mismatch_errors() {
    let mut wkb = le_header(0x8000_0004); // MultiPoint Z
    wkb.extend_from_slice(&1u32.to_le_bytes());
    wkb.extend_from_slice(&wkb_of("POINT (1 2)"));
    assert!(wkb_to_wkt(&wkb).is_err());
}

// ── MultiLineString edge cases ────────────────────────────────────────────────

#[test]
fn multilinestring_empty_member() {
    // A MultiLineString whose sole member is an empty (0-point) LineString.
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&5u32.to_le_bytes()); // MultiLineString
    wkb.extend_from_slice(&1u32.to_le_bytes()); // 1 member
    wkb.push(0x01);
    wkb.extend_from_slice(&2u32.to_le_bytes()); // LineString
    wkb.extend_from_slice(&0u32.to_le_bytes()); // 0 points
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "MULTILINESTRING (EMPTY)");
}

#[test]
fn multilinestring_wrong_subtype_errors() {
    // A MultiLineString whose member is a Point — must be rejected.
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&5u32.to_le_bytes()); // MultiLineString
    wkb.extend_from_slice(&1u32.to_le_bytes()); // 1 member
    wkb.push(0x01);
    wkb.extend_from_slice(&1u32.to_le_bytes()); // Point (not LineString)
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&2.0f64.to_le_bytes());
    assert!(wkb_to_wkt(&wkb).is_err());
}

#[test]
fn multilinestring_child_dimension_mismatch_errors() {
    let mut wkb = le_header(5); // MultiLineString XY
    wkb.extend_from_slice(&1u32.to_le_bytes());
    wkb.extend_from_slice(&wkb_of("LINESTRING Z (0 0 0, 1 1 1)"));
    assert!(wkb_to_wkt(&wkb).is_err());
}

// ── MultiPolygon edge cases ───────────────────────────────────────────────────

#[test]
fn multipolygon_empty_member() {
    // A MultiPolygon whose sole member is an empty (0-ring) Polygon.
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&6u32.to_le_bytes()); // MultiPolygon
    wkb.extend_from_slice(&1u32.to_le_bytes()); // 1 member
    wkb.push(0x01);
    wkb.extend_from_slice(&3u32.to_le_bytes()); // Polygon
    wkb.extend_from_slice(&0u32.to_le_bytes()); // 0 rings
    assert_eq!(wkb_to_wkt(&wkb).unwrap(), "MULTIPOLYGON (EMPTY)");
}

#[test]
fn multipolygon_wrong_subtype_errors() {
    // A MultiPolygon whose member is a Point — must be rejected.
    let mut wkb = vec![0x01u8];
    wkb.extend_from_slice(&6u32.to_le_bytes()); // MultiPolygon
    wkb.extend_from_slice(&1u32.to_le_bytes()); // 1 member
    wkb.push(0x01);
    wkb.extend_from_slice(&1u32.to_le_bytes()); // Point (not Polygon)
    wkb.extend_from_slice(&1.0f64.to_le_bytes());
    wkb.extend_from_slice(&2.0f64.to_le_bytes());
    assert!(wkb_to_wkt(&wkb).is_err());
}

#[test]
fn multipolygon_child_dimension_mismatch_errors() {
    let mut wkb = le_header(6); // MultiPolygon XY
    wkb.extend_from_slice(&1u32.to_le_bytes());
    wkb.extend_from_slice(&wkb_of("POLYGON Z ((0 0 0, 1 0 0, 1 1 0, 0 0 0))"));
    assert!(wkb_to_wkt(&wkb).is_err());
}
